# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-04-19 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0004_auto_20190419_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdog',
            name='status',
            field=models.CharField(default='u', max_length=255),
        ),
    ]
